import re

x = "['ALCOHOL','BREAD','CAKES AND SWEETS','FRUIT AND VEGETABLES','MILK AND DAIRY PRODUCTS'],['BREAD','CAKES AND SWEETS','DIPS','MILK AND DAIRY PRODUCTS','PASTA'],['HOT FOOD','OTHERS'],['ALCOHOL','BREAD','CAKES AND SWEETS'],['BREAD','CAKES AND SWEETS','FRUIT AND VEGETABLES','MILK AND DAIRY PRODUCTS','OTHERS','SNACKS','SPICES','WATER'],['BREAD','CAKES AND SWEETS','FRUIT AND VEGETABLES'],['BREAD','CAKES AND SWEETS']"

d = '],['
print([y+d for y in x.split(d)])

print(re.split('(\],\[)', x))

x1 = [['ALCOHOL','BREAD','CAKES AND SWEETS','FRUIT AND VEGETABLES','MILK AND DAIRY PRODUCTS'],['BREAD','CAKES AND SWEETS','DIPS','MILK AND DAIRY PRODUCTS','PASTA'],['HOT FOOD','OTHERS'],['ALCOHOL','BREAD','CAKES AND SWEETS'],['BREAD','CAKES AND SWEETS','FRUIT AND VEGETABLES','MILK AND DAIRY PRODUCTS','OTHERS','SNACKS','SPICES','WATER'],['BREAD','CAKES AND SWEETS','FRUIT AND VEGETABLES'],['BREAD','CAKES AND SWEETS']]
for x in x1:
    print(x)
